"""Add reviewer audit logs

Revision ID: 4b30b048951d
Revises: a5cf32742ac7
Create Date: 2026-08-18 22:04:35.430254

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b30b048951d'
down_revision: Union[str, Sequence[str], None] = 'a5cf32742ac7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reviewer_audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor_reviewer_id', sa.Integer(), nullable=False),
    sa.Column('target_reviewer_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('details', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_reviewer_id'], ['reviewers.id'], ),
    sa.ForeignKeyConstraint(['target_reviewer_id'], ['reviewers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reviewer_audit_logs_actor_reviewer_id'), 'reviewer_audit_logs', ['actor_reviewer_id'], unique=False)
    op.create_index(op.f('ix_reviewer_audit_logs_id'), 'reviewer_audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_reviewer_audit_logs_target_reviewer_id'), 'reviewer_audit_logs', ['target_reviewer_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reviewer_audit_logs_target_reviewer_id'), table_name='reviewer_audit_logs')
    op.drop_index(op.f('ix_reviewer_audit_logs_id'), table_name='reviewer_audit_logs')
    op.drop_index(op.f('ix_reviewer_audit_logs_actor_reviewer_id'), table_name='reviewer_audit_logs')
    op.drop_table('reviewer_audit_logs')
    # ### end Alembic commands ###
