"""Add report review history

Revision ID: 8b288400f369
Revises: decc31418750
Create Date: 2026-08-16 15:24:04.937866

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b288400f369'
down_revision: Union[str, Sequence[str], None] = 'decc31418750'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('report_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('previous_status', sa.String(length=30), nullable=False),
    sa.Column('new_status', sa.String(length=30), nullable=False),
    sa.Column('decision', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('reviewer', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_reviews_id'), 'report_reviews', ['id'], unique=False)
    op.create_index(op.f('ix_report_reviews_report_id'), 'report_reviews', ['report_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_report_reviews_report_id'), table_name='report_reviews')
    op.drop_index(op.f('ix_report_reviews_id'), table_name='report_reviews')
    op.drop_table('report_reviews')
    # ### end Alembic commands ###
