"""Add reviewers authentication

Revision ID: a5cf32742ac7
Revises: c80b2235ef88
Create Date: 2026-08-18 20:44:08.834098

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5cf32742ac7'
down_revision: Union[str, Sequence[str], None] = 'c80b2235ef88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reviewers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reviewers_id'), 'reviewers', ['id'], unique=False)
    op.create_index(op.f('ix_reviewers_username'), 'reviewers', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reviewers_username'), table_name='reviewers')
    op.drop_index(op.f('ix_reviewers_id'), table_name='reviewers')
    op.drop_table('reviewers')
    # ### end Alembic commands ###
