"""Add AI risk analysis history

Revision ID: c80b2235ef88
Revises: 8b288400f369
Create Date: 2026-08-17 21:15:33.885557

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c80b2235ef88'
down_revision: Union[str, Sequence[str], None] = '8b288400f369'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('report_ai_analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('level', sa.String(length=20), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('reasons', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_ai_analyses_id'), 'report_ai_analyses', ['id'], unique=False)
    op.create_index(op.f('ix_report_ai_analyses_report_id'), 'report_ai_analyses', ['report_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_report_ai_analyses_report_id'), table_name='report_ai_analyses')
    op.drop_index(op.f('ix_report_ai_analyses_id'), table_name='report_ai_analyses')
    op.drop_table('report_ai_analyses')
    # ### end Alembic commands ###
